apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-mgmt
  template:
    metadata:
      labels:
        app: restaurant-mgmt
    spec:
      containers:
      - name: restaurant-mgmt
        image: thanishma/restaurants-app:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-mgmt
spec:
  type: NodePort
  selector:
    app: restaurant-mgmt
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 32000

    
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restaurant-ingress
spec:
  rules:
  - host: restaurant.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: restaurant-mgmt
            port:
              number: 8000
